apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-service-deployment
  labels:
    app: appointment-scheduling-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduling-service
  template:
    metadata:
      labels:
        app: appointment-scheduling-service
    spec:
      containers:
      - name: appointment-scheduling-service
        image: 692859924695.dkr.ecr.ap-southeast-1.amazonaws.com/nisurim/appointment-service:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
