apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-deployment
  labels:
    app: patient-record-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
      - name: patient-record-service
        image: 692859924695.dkr.ecr.ap-southeast-1.amazonaws.com/nisurim/patient-record-service:latest
        ports:
        - containerPort: 8083
