apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    app: aggregator-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: aggregator-service
