apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: notification-service
