apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
  labels:
    app: patient-record-service
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: patient-record-service
